name: football2vec
channels:
  - conda-forge
  - defaults
dependencies:
  - gensim=3.8.3
  - matplotlib=3.3.2=0
  - numba=0.53.1
  - numpy=1.19.2
  - pandas=1.1.3
  - pillow=8.0.1
  - plotly=4.14.3
  - regex=2020.4.4
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - streamlit=0.79.0
  - tqdm=4.51.0
  - umap-learn=0.5.1
  - pip:
    - chart_studio

